name: solana_dex_analytics
version: "1.0.0"
config-version: 2

profile: solana_dex_analytics

require-dbt-version: ">=1.8.0,<2.0.0"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  solana_raw_dataset: "{{ env_var('BQ_DATASET_RAW', 'solana_raw') }}"

models:
  solana_dex_analytics:
    staging:
      +materialized: table
      +schema: solana_staging
    intermediate:
      +materialized: table
      +schema: solana_intermediate
    marts:
      +materialized: view
      +schema: solana_marts
