name: solana_dex_analytics
version: "1.0.0"
config-version: 2

profile: solana_dex_analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  solana_dex_analytics:
    staging:
      +schema: "{{ env_var('BQ_DATASET_STAGING', 'solana_staging') }}"
      +materialized: view
    intermediate:
      +schema: "{{ env_var('BQ_DATASET_INTERMEDIATE', 'solana_intermediate') }}"
      +materialized: view
    marts:
      +schema: "{{ env_var('BQ_DATASET_MARTS', 'solana_marts') }}"
      +materialized: table
