solana_dex_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: solana-analytics-498121
      dataset: solana_staging
      location: europe-west3
      threads: 4
      timeout_seconds: 300
